name: Flutter CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Deploy to Firebase App Distribution
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute --app ${{ secrets.APPID }} --token ${{ secrets.TOKEN }} --groups testers --file build/app/outputs/flutter-apk/app-release.apk
        env:
          FIREBASE_TOKEN: ${{ secrets.TOKEN }}
